# Generated by Django 5.0.6 on 2024-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzactie',
            name='balanta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
