# Generated by Django 5.0.6 on 2024-06-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0002_alter_tranzactie_balanta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzactie',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Gifts and Donations', 'Gifts and Donations'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tranzactie',
            name='expense_or_income',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
    ]
